branches:
  only:
    - /.*/
language: ruby
rvm:
- 2.1.7
sudo: false
cache: bundler
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
bundler_args: "--with test"
before_install:
- nvm install # Install node from .nvmrc
- nvm use # Use node version from .nvmrc
- nvm install
- npm install -g surge

after_success:
- test $TRAVIS_BRANCH == "gh-pages" && test $TRAVIS_PULL_REQUEST == "false" && surge --project ./public --domain http://chrismetcalf.net
